# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 40b03a7674145fd86e089149c0884c1ff20a46e95042a954603a5867c14ad92103263f75d14381117b4f1ccc263735fcb327df2c4df2eb976e5faddd4edfc3ac

test:
  secret_key_base: 578bb814ca0094e193647882ecfa260b77d2a640fe6ffbb3cc85dcb68e5d94db91a7dc62b43e5982276e482b795e17bda26971adaeae77ffe264e19309f8bd8c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
